"""Deterministic replay/backtest runner — roadmap Phase 8.

The runner ORCHESTRATES landed deterministic code; it mints no protected object itself.
For one ``ReplayScenario`` it walks the real pipeline, never bypassing a boundary:

    strategy.generate(ctx)                      # candidates only (fail-closed on data)
      -> GatewayRequest -> ExecutionGateway.validate()   # the only ValidatedTradeIntent path
      -> mint_order_ticket()                    # the only OrderTicket path
      -> record submit attempt (BEFORE broker)  # Phase-4 persist-before-call
      -> mint_broker_submit_intent()            # the only BrokerSubmitIntent path
      -> broker.submit_order()                  # fakes accept BrokerSubmitIntent only
      -> mint_execution_report()                # the only ExecutionReport path
      -> audit store append                     # rejections/failures audited, never dropped

Determinism: every timestamp is the scenario's explicit ``as_of`` / caller ``recorded_at``;
no wall clock, no randomness, no network. Fail-closed: a missing-data strategy error, a
gateway rejection, a malformed gateway assembly, or a broker failure all produce a typed
result and an audit record — never a silent drop and never a crash out of the runner.

Safety boundary (Constitution §0.1; AGENTS.md; roadmap Do-Not-Cross): the scenario supplies
only the (deterministic) strategy inputs and safety state. The candidate is generated by
deterministic strategy code, and every protected object is minted exclusively by the
gateway/routing/submission helpers. Nothing here lets a raw dict, prose, or an
earlier-stage object become a protected execution object.
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime
from decimal import Decimal

from pydantic import ValidationError

from brokers import (
    BrokerDisconnectError,
    BrokerError,
    BrokerRejectedError,
    BrokerTimeoutError,
    audit_artifact_from_broker_error,
)
from brokers.base import BrokerFill
from data import MarketDataUnavailableError
from gateway import (
    ExecutionGateway,
    GatewayRequest,
    mint_broker_submit_intent,
    mint_execution_report,
    mint_order_ticket,
)
from schemas import (
    AuditArtifact,
    BrokerSubmitIntent,
    OrderLifecycleState,
    OrderType,
    ReasonCode,
    RouteMode,
)
from schemas.base import HermesModel
from storage import AuditStore, DuplicateIdempotencyKeyError, StoredEvent

from .results import UNRESOLVED_OUTCOMES, ReplayOutcome, ReplayResult, ReplayRun
from .scenario import ReplayScenario

# One stateless gateway instance is safe to reuse (it holds no mutable state).
_GATEWAY = ExecutionGateway()

# Reason codes that mark an open-short / protection hazard surfaced by the gateway.
_HAZARD_CODES: frozenset[ReasonCode] = frozenset(
    {ReasonCode.PROTECTION_HIERARCHY_VIOLATION, ReasonCode.BROKEN_SPREAD_STATE}
)

# Broker error type -> replay outcome (fail-closed default: a rejection).
_BROKER_OUTCOME: dict[type[BrokerError], ReplayOutcome] = {
    BrokerRejectedError: ReplayOutcome.BROKER_REJECTED,
    BrokerDisconnectError: ReplayOutcome.BROKER_DISCONNECTED,
    BrokerTimeoutError: ReplayOutcome.BROKER_TIMEOUT,
}

_LIFECYCLE_OUTCOME: dict[OrderLifecycleState, ReplayOutcome] = {
    OrderLifecycleState.FILLED: ReplayOutcome.FILLED,
    OrderLifecycleState.PARTIAL_FILL: ReplayOutcome.PARTIAL_FILL,
    OrderLifecycleState.WORKING: ReplayOutcome.WORKING,
}


class _Audit:
    """Append-only audit accumulator for one scenario run.

    Threads the deterministic ``recorded_at`` through every append and collects the
    resulting event ids/seqs so the ``ReplayResult`` exposes a full audit trail.
    """

    def __init__(self, store: AuditStore, *, recorded_at: datetime) -> None:
        self._store = store
        self._recorded_at = recorded_at
        self.record_ids: list[str] = []
        self.seqs: list[int] = []

    def add(self, obj: HermesModel, *, created_at: datetime) -> StoredEvent:
        event = self._store.append(obj, created_at=created_at, recorded_at=self._recorded_at)
        self.record_ids.append(event.record_id)
        self.seqs.append(event.seq)
        return event

    def add_submit_attempt(self, intent: BrokerSubmitIntent) -> StoredEvent:
        event = self._store.record_submit_attempt(intent, recorded_at=self._recorded_at)
        self.record_ids.append(event.record_id)
        self.seqs.append(event.seq)
        return event


def _replay_artifact(
    scenario: ReplayScenario,
    *,
    suffix: str,
    decision: str,
    reason_codes: tuple[ReasonCode, ...],
    detail: str,
) -> AuditArtifact:
    """Build a deterministic replay AuditArtifact (id derived from scenario + suffix)."""
    return AuditArtifact(
        artifact_id=f"replay-{scenario.scenario_id}-{suffix}",
        created_at=scenario.as_of,
        decision=decision,
        reason_codes=reason_codes,
        detail=detail,
    )


def _compute_pnl(
    *,
    filled_contracts: int,
    avg_fill_price: Decimal | None,
    multiplier: int,
    slippage_per_contract: Decimal,
    settlement_value_per_spread: Decimal | None,
) -> tuple[Decimal, Decimal, Decimal | None, bool]:
    """Deterministic Decimal PnL/slippage. Returns (credit, slippage_cost, pnl, supported).

    credit_captured  = avg_fill_price * filled * multiplier            (0 when unpriced)
    slippage_cost    = slippage_per_contract * filled * multiplier
    realized_pnl     = (avg_fill_price - settlement) * filled * multiplier - slippage_cost
                       reported ONLY when an explicit settlement assumption is supplied;
                       otherwise pnl is unsupported (reported, not guessed).
    """
    priced = avg_fill_price if avg_fill_price is not None else Decimal("0")
    credit_captured = priced * filled_contracts * multiplier
    slippage_cost = slippage_per_contract * filled_contracts * multiplier
    if settlement_value_per_spread is None:
        return credit_captured, slippage_cost, None, False
    gross = (priced - settlement_value_per_spread) * filled_contracts * multiplier
    return credit_captured, slippage_cost, gross - slippage_cost, True


def _passed(scenario: ReplayScenario, outcome: ReplayOutcome, *, protection_hazard: bool) -> bool:
    if outcome is not scenario.expected_outcome:
        return False
    if scenario.expect_protection_hazard and not protection_hazard:
        return False
    return True


def run_scenario(
    scenario: ReplayScenario,
    store: AuditStore,
    *,
    recorded_at: datetime,
) -> ReplayResult:
    """Replay one scenario end-to-end and return a stable, serializable result."""
    audit = _Audit(store, recorded_at=recorded_at)
    as_of = scenario.as_of

    # -- 1. strategy generation (fail-closed on missing market data) ----------
    ctx = scenario.build_context()
    try:
        proposals = scenario.strategy.generate(ctx)
    except MarketDataUnavailableError as exc:
        audit.add(
            _replay_artifact(
                scenario,
                suffix="data-unavailable",
                decision="NO_TRADE",
                reason_codes=(),
                detail=f"strategy failed closed on missing market data: {exc}",
            ),
            created_at=as_of,
        )
        return _finalize(
            scenario,
            outcome=ReplayOutcome.DATA_UNAVAILABLE,
            audit=audit,
        )

    if not proposals:
        audit.add(
            _replay_artifact(
                scenario,
                suffix="no-candidate",
                decision="NO_TRADE",
                reason_codes=(),
                detail="strategy produced no candidate (entry window / IVR / DTE filter)",
            ),
            created_at=as_of,
        )
        return _finalize(scenario, outcome=ReplayOutcome.NO_CANDIDATE, audit=audit)

    candidate = proposals[0].candidate

    # -- 2. gateway validation (the only path to ValidatedTradeIntent) --------
    # Build the request explicitly from the scenario's typed safety state. The candidate
    # comes from deterministic strategy code; every other field is deterministic safety
    # state. A malformed field (e.g. a smuggled raw dict) raises here and fails closed.
    safety = scenario.safety
    try:
        request = GatewayRequest(
            candidate=candidate,
            as_of=as_of,
            account=safety.account,
            heat=safety.heat,
            drawdown=safety.drawdown,
            instrument=safety.instrument,
            spread_contract=safety.spread_contract,
            underlying_policy=safety.underlying_policy,
            data_snapshot=safety.data_snapshot,
            reconciliation=safety.reconciliation,
            liquidity=safety.liquidity,
            execution_quality=safety.execution_quality,
            concentration=safety.concentration,
            protection=safety.protection,
            multi_leg=safety.multi_leg,
            strategy_stage=safety.strategy_stage,
            feed_certification=safety.feed_certification,
            event_calendar=safety.event_calendar,
        )
    except (ValueError, ValidationError) as exc:
        # A malformed gateway assembly is a fail-closed rejection, not a crash.
        artifact = _replay_artifact(
            scenario,
            suffix="gateway-assembly",
            decision="REJECT",
            reason_codes=(ReasonCode.INTERNAL_CONTRADICTION,),
            detail=f"gateway request could not be assembled: {exc}",
        )
        audit.add(artifact, created_at=as_of)
        return _finalize(
            scenario,
            outcome=ReplayOutcome.GATEWAY_REJECTED,
            audit=audit,
            candidate_rationale_id=candidate.rationale_id,
            gateway_evaluated=True,
            reason_codes=(ReasonCode.INTERNAL_CONTRADICTION,),
        )

    audit.add(request, created_at=as_of)
    decision = _GATEWAY.validate(request)

    if not decision.is_approved:
        rejection = decision.rejection
        assert rejection is not None  # is_approved False => rejection present
        audit.add(rejection, created_at=rejection.created_at)
        hazard = any(code in _HAZARD_CODES for code in decision.reason_codes)
        return _finalize(
            scenario,
            outcome=ReplayOutcome.GATEWAY_REJECTED,
            audit=audit,
            candidate_rationale_id=candidate.rationale_id,
            gateway_evaluated=True,
            reason_codes=decision.reason_codes,
            protection_hazard=hazard,
        )

    validated = decision.approved
    assert validated is not None
    audit.add(validated, created_at=as_of)

    # -- 3-4. routing + submit-intent mint (only OrderTicket / BrokerSubmitIntent paths) -
    # These sanctioned mints can themselves raise (rejected route, stale/future ticket,
    # bad attempt_counter, missing limit_price). On the approved path they should not, but
    # the runner must never crash out: any mint failure is a fail-closed rejection that is
    # audited as an INTERNAL_CONTRADICTION rather than propagated.
    try:
        ticket = mint_order_ticket(validated, scenario.routing_state, created_at=as_of)
        audit.add(ticket, created_at=ticket.created_at)
        # Submit intent is persisted BEFORE the broker call (Phase-4 rule).
        intent = mint_broker_submit_intent(
            ticket,
            attempt_counter=1,
            submit_mode=scenario.submit_mode,
            limit_price=scenario.limit_price,
            as_of=as_of,
        )
    except (ValueError, TypeError) as exc:
        audit.add(
            _replay_artifact(
                scenario,
                suffix="route-or-submit-mint",
                decision="REJECT",
                reason_codes=(ReasonCode.INTERNAL_CONTRADICTION,),
                detail=f"routing/submit-intent mint failed closed: {exc}",
            ),
            created_at=as_of,
        )
        return _finalize(
            scenario,
            outcome=ReplayOutcome.GATEWAY_REJECTED,
            audit=audit,
            candidate_rationale_id=candidate.rationale_id,
            gateway_evaluated=True,
            gateway_approved=True,
            reason_codes=(ReasonCode.INTERNAL_CONTRADICTION,),
        )
    audit.add_submit_attempt(intent)

    # -- 5. broker submit (fakes accept BrokerSubmitIntent only; may raise) ---
    submit_attempts = 1
    try:
        fill = scenario.broker.submit_order(intent)
    except BrokerError as exc:
        artifact = audit_artifact_from_broker_error(
            exc,
            artifact_id=f"replay-{scenario.scenario_id}-broker-{exc.reason_code.value}",
            created_at=as_of,
        )
        audit.add(artifact, created_at=as_of)
        outcome = _BROKER_OUTCOME.get(type(exc), ReplayOutcome.BROKER_REJECTED)
        return _finalize(
            scenario,
            outcome=outcome,
            audit=audit,
            candidate_rationale_id=candidate.rationale_id,
            gateway_evaluated=True,
            gateway_approved=True,
            reason_codes=(exc.reason_code,),
            order_type=ticket.order_type,
            route_mode=scenario.routing_state.route_mode,
            submit_attempts=submit_attempts,
            idempotency_key=intent.idempotency_key,
            requested_contracts=candidate.short_leg.contracts,
        )

    # -- 6. execution report (the only path to ExecutionReport) ---------------
    # Minting can reject a malformed fill (overfill, FILLED-without-price, bad timestamp
    # ordering). The broker order is already placed, so a failure here must NOT crash the
    # run and drop the broker response: it is audited and the persisted submit is left
    # visible as an unresolved REPORT_REJECTED for restart reconciliation.
    try:
        report = mint_execution_report(
            intent,
            broker_order_id=fill.broker_order_id,
            lifecycle_state=fill.lifecycle_state,
            filled_contracts=fill.filled_contracts,
            avg_fill_price=fill.avg_fill_price,
            fill_timestamp=fill.fill_timestamp,
            completed_at=fill.completed_at,
        )
    except (ValueError, TypeError) as exc:
        audit.add(
            _replay_artifact(
                scenario,
                suffix="execution-report",
                decision="REJECT",
                reason_codes=(ReasonCode.INTERNAL_CONTRADICTION,),
                detail=(
                    f"execution report mint failed closed: {exc}; broker order "
                    f"{fill.broker_order_id.value} is unresolved (no report recorded)"
                ),
            ),
            created_at=as_of,
        )
        return _finalize(
            scenario,
            outcome=ReplayOutcome.REPORT_REJECTED,
            audit=audit,
            candidate_rationale_id=candidate.rationale_id,
            gateway_evaluated=True,
            gateway_approved=True,
            reason_codes=(ReasonCode.INTERNAL_CONTRADICTION,),
            order_type=ticket.order_type,
            route_mode=scenario.routing_state.route_mode,
            submit_attempts=submit_attempts,
            idempotency_key=intent.idempotency_key,
            broker_order_id=fill.broker_order_id.value,
            requested_contracts=candidate.short_leg.contracts,
        )
    audit.add(report, created_at=as_of)

    # -- 7. duplicate-submit drill: same idempotency key must not double-order -
    first_order_id = fill.broker_order_id.value
    duplicate_created_second_order = False
    store_deduped_resubmit = False
    for i in range(scenario.resubmit_attempts):
        submit_attempts += 1
        try:
            resubmit_fill: BrokerFill = scenario.broker.submit_order(intent)
        except BrokerError as exc:
            # A resubmit (same idempotency key) that fails is still audited — never a
            # silent drop. The original fill/report already stand; no second order exists.
            audit.add(
                audit_artifact_from_broker_error(
                    exc,
                    artifact_id=f"replay-{scenario.scenario_id}-resubmit-{i}-broker-{exc.reason_code.value}",
                    created_at=as_of,
                ),
                created_at=as_of,
            )
            continue
        if resubmit_fill.broker_order_id.value != first_order_id:
            duplicate_created_second_order = True
        # Same-key retries are transport retries covered by the ORIGINAL persisted submit
        # intent: the store refuses a second persist for the same idempotency_key, proving
        # the retry never becomes a distinct order.
        try:
            audit.add_submit_attempt(intent)
        except DuplicateIdempotencyKeyError:
            store_deduped_resubmit = True

    outcome = _LIFECYCLE_OUTCOME.get(fill.lifecycle_state, ReplayOutcome.WORKING)
    credit, slippage_cost, realized_pnl, pnl_supported = _compute_pnl(
        filled_contracts=fill.filled_contracts,
        avg_fill_price=fill.avg_fill_price,
        multiplier=candidate.multiplier,
        slippage_per_contract=scenario.fill_assumptions.slippage_per_contract,
        settlement_value_per_spread=scenario.fill_assumptions.settlement_value_per_spread,
    )

    return _finalize(
        scenario,
        outcome=outcome,
        audit=audit,
        candidate_rationale_id=candidate.rationale_id,
        gateway_evaluated=True,
        gateway_approved=True,
        order_type=ticket.order_type,
        route_mode=scenario.routing_state.route_mode,
        submit_attempts=submit_attempts,
        idempotency_key=intent.idempotency_key,
        broker_order_id=first_order_id,
        lifecycle_state=fill.lifecycle_state,
        requested_contracts=fill.requested_contracts,
        filled_contracts=fill.filled_contracts,
        avg_fill_price=fill.avg_fill_price,
        duplicate_created_second_order=duplicate_created_second_order,
        store_deduped_resubmit=store_deduped_resubmit,
        credit_captured=credit,
        slippage_cost=slippage_cost,
        realized_pnl=realized_pnl,
        pnl_supported=pnl_supported,
    )


def _finalize(
    scenario: ReplayScenario,
    *,
    outcome: ReplayOutcome,
    audit: _Audit,
    candidate_rationale_id: str | None = None,
    gateway_evaluated: bool = False,
    gateway_approved: bool = False,
    reason_codes: tuple[ReasonCode, ...] = (),
    protection_hazard: bool = False,
    order_type: OrderType | None = None,
    route_mode: RouteMode | None = None,
    submit_attempts: int = 0,
    idempotency_key: str | None = None,
    broker_order_id: str | None = None,
    lifecycle_state: OrderLifecycleState | None = None,
    requested_contracts: int | None = None,
    filled_contracts: int | None = None,
    avg_fill_price: Decimal | None = None,
    duplicate_created_second_order: bool = False,
    store_deduped_resubmit: bool = False,
    credit_captured: Decimal | None = None,
    slippage_cost: Decimal | None = None,
    realized_pnl: Decimal | None = None,
    pnl_supported: bool = False,
) -> ReplayResult:
    """Assemble the immutable ReplayResult (single construction point)."""
    return ReplayResult(
        scenario_id=scenario.scenario_id,
        scenario_name=scenario.name,
        outcome=outcome,
        expected_outcome=scenario.expected_outcome,
        passed=_passed(scenario, outcome, protection_hazard=protection_hazard),
        is_failure_drill=scenario.is_failure_drill,
        generated_candidate_count=0 if candidate_rationale_id is None else 1,
        candidate_rationale_id=candidate_rationale_id,
        gateway_evaluated=gateway_evaluated,
        gateway_approved=gateway_approved,
        reason_codes=reason_codes,
        protection_hazard=protection_hazard,
        order_type=order_type,
        route_mode=route_mode,
        submit_attempts=submit_attempts,
        idempotency_key=idempotency_key,
        broker_order_id=broker_order_id,
        lifecycle_state=lifecycle_state,
        requested_contracts=requested_contracts,
        filled_contracts=filled_contracts,
        avg_fill_price=avg_fill_price,
        unresolved=outcome in UNRESOLVED_OUTCOMES,
        duplicate_created_second_order=duplicate_created_second_order,
        store_deduped_resubmit=store_deduped_resubmit,
        credit_captured=credit_captured,
        slippage_cost=slippage_cost,
        realized_pnl=realized_pnl,
        pnl_supported=pnl_supported,
        audit_record_ids=tuple(audit.record_ids),
        audit_event_seqs=tuple(audit.seqs),
    )


def run_scenarios(
    scenarios: Sequence[ReplayScenario],
    store: AuditStore,
    *,
    recorded_at: datetime,
) -> ReplayRun:
    """Replay an ordered suite and aggregate pass counts + run-level PnL/drawdown."""
    results = tuple(run_scenario(s, store, recorded_at=recorded_at) for s in scenarios)

    cumulative = Decimal("0")
    peak = Decimal("0")
    max_drawdown = Decimal("0")
    for result in results:
        if result.pnl_supported and result.realized_pnl is not None:
            cumulative += result.realized_pnl
            peak = max(peak, cumulative)
            max_drawdown = max(max_drawdown, peak - cumulative)

    scenarios_passed = sum(1 for r in results if r.passed)
    replay_scenarios_passed = sum(1 for r in results if r.passed and not r.is_failure_drill)
    failure_drills_total = sum(1 for r in results if r.is_failure_drill)
    failure_drills_passed = sum(1 for r in results if r.is_failure_drill and r.passed)

    return ReplayRun(
        results=results,
        scenarios_total=len(results),
        scenarios_passed=scenarios_passed,
        replay_scenarios_passed=replay_scenarios_passed,
        failure_drills_total=failure_drills_total,
        failure_drills_passed=failure_drills_passed,
        cumulative_realized_pnl=cumulative,
        max_drawdown=max_drawdown,
    )
